public class PopReminderConstant {
	public static final Integer PROCESS_REMINDER_BATCH_SIZE = 20;
    public static final Integer DAYS_FROM_IN_DUE_REMINDERS = -3;
    public static final Integer DAYS_UNTIL_IN_DUE_REMINDERS = 2;
    public static final String HIGH_SEVERITY = 'High';
    public static final String LOW_SEVERITY = 'Low';
    public static final String REMINDER_DUE = 'Due';
    public static final String REMINDER_ALMOST_DUE = 'Almost Due';
    public static final String REMINDER_COUNTING_DOWN = 'Counting Down';
    public static final String EMAIL_BODY_TABLE_STYLE = 'background-color:#eee;border-collapse:collapse';
    public static final String EMAIL_BODY_HEADER_STYLE = 'background-color:#000;color:white;width:20%';
    public static final String EMAIL_BODY_HEADER_LONG_WIDTH_STYLE = 'background-color:#000;color:white;width:50%';
    public static final String EMAIL_BODY_ROW_STYLE = 'padding:5px;border:1px solid #000';
}