public class PopReminderConstant {
	public static final Integer PROCESS_REMINDER_BATCH_SIZE = 20;
    public static final String HIGH_SEVERITY = 'High';
    public static final String LOW_SEVERITY = 'Low';
    public static final String REMINDER_DUE = 'Due';
    public static final String REMINDER_ALMOST_DUE = 'Almost Due';
    public static final String REMINDER_COUNTING_DOWN = 'Counting Down';
}